complain audibly when argument not supplied; echo on stderr when writing error messages

diff --git a/tests/create-test b/tests/create-test
--- a/tests/create-test
+++ b/tests/create-test
@@ -3,17 +3,18 @@
 TESTFILES="Makefile.am scanner.l parser.y .cvsignore test.input"
 
 if [ ! $# -eq 1 ] ; then
+   echo 1>&2 Usage: $0 test-name
    exit 1
 fi
 
 if test -e "$1" ; then
-    echo "$1 exists already"
+    echo 1>&2 "$1 exists already"
     exit 1
 fi
 
 mkdir $1 
 if test "$?" -ne 0 ; then
-    echo "mkdir $1 failed"
+    echo 1>&2 "mkdir $1 failed"
     exit 1
 fi
 
