Cleaned up the output of the tests.

diff --git a/tests/Makefile.in b/tests/Makefile.in
--- a/tests/Makefile.in
+++ b/tests/Makefile.in
@@ -5,24 +5,56 @@ TESTDIRS= @TESTDIRS@
 
 srcdir= @srcdir@
 
-all: check
 
-check: 
-	for dir in $(TESTDIRS) ; do \
-       (cd "$$dir" && $(MAKE) check ) || echo Test $$dir failed ; \
+all: build
+
+build:
+	@for dir in $(TESTDIRS) ; do \
+       (cd "$$dir" && $(MAKE) ) ; \
     done
+	@echo "Type 'make check' to run all tests."
+
+check:
+	@nok=0;\
+    nfail=0;\
+    nskip=0;\
+    for dir in $(TESTDIRS) ; do \
+       echo -n Executing "$$dir" ; \
+       dot=$$((30-$${#dir})); \
+       while (( dot )); do \
+           echo -n '.'; \
+           dot=$$((dot-1)); \
+       done; \
+       ( cd "$$dir" && $(MAKE) check  > OUTPUT 2>&1 ) ; \
+       case $$? in \
+            0)  echo OK.; \
+                 nok=$$((nok+1)) ; \
+                 continue; \
+                 ;; \
+            1)  echo "FAILED. See $$dir/OUTPUT for details." ; \
+                 nfail=$$((nfail+1)) ; \
+                 ;; \
+            2)  echo "SKIPPED. See $$dir/OUTPUT for details."; \
+                 nskip=$$((nskip+1)) ; \
+                 ;; \
+       esac; \
+    done ; \
+    echo "Results: "; \
+    echo "    Tests OK:        $$nok"; \
+    echo "    Tests SKIPPED:   $$nskip"; \
+    echo "    Tests FAILED:    $$nfail" ;
 
 distclean: clean
-	for dir in $(TESTDIRS) ; do \
+	@for dir in $(TESTDIRS) ; do \
        if test -f "$$dir/Makefile" ; then \
           (cd "$$dir" && $(MAKE) distclean ) ; \
-       fi \
+       fi; \
     done
 	rm -f config.h config.status config.log Makefile
 
 clean:
-	for dir in $(TESTDIRS) ; do \
+	@for dir in $(TESTDIRS) ; do \
        if test -f "$$dir/Makefile" ; then \
            (cd "$$dir" && $(MAKE) clean ) ; \
-       fi \
+       fi ; \
     done
