build: Add stage2scan.c and byte comparison check for bootstrap.
With stage1scan.c being deterministic, it's possible to add a bootstrap
check that ensures the generated flex program can build the scanner of
itself flawlessly. The check is performed on native build only.

Code is partly inspired from GCC's makefile.

Signed-off-by: Kang-Che Sung <explorer09@gmail.com>

diff --git a/src/Makefile.am b/src/Makefile.am
--- a/src/Makefile.am
+++ b/src/Makefile.am
@@ -8,6 +8,9 @@ m4 = @M4@
 bin_PROGRAMS = flex
 if ENABLE_BOOTSTRAP
 noinst_PROGRAMS = stage1flex
+if !CROSS
+noinst_DATA = stage2compare
+endif
 endif
 
 if ENABLE_LIBFL
@@ -106,7 +109,9 @@ EXTRA_DIST = \
 
 MOSTLYCLEANFILES = \
 	$(SKELINCLUDES) \
-	stage1scan.c
+	stage1scan.c \
+	stage2scan.c \
+	stage2compare
 
 CLEANFILES = stage1flex$(EXEEXT)
 
@@ -137,6 +142,24 @@ stage1scan.c: scan.l stage1flex$(EXEEXT)
 	( cd $(srcdir) && $(abs_builddir)/stage1flex$(EXEEXT) \
 	  $(AM_LFLAGS) $(LFLAGS) -o scan.c -t scan.l ) >$@ || \
 	{ s=$$?; rm -f $@; exit $$s; }
+
+# Unlike stage1scan.c, we leave stage2scan.c intact when the generation
+# fails. This allow users to examine generation errors.
+stage2scan.c: scan.l flex$(EXEEXT) stage1scan.c
+	( cd $(srcdir) && $(abs_builddir)/flex$(EXEEXT) \
+	  $(AM_LFLAGS) $(LFLAGS) -o scan.c -t scan.l ) >$@
+
+stage2compare: stage1scan.c
+	@rm -f stage2scan.c; \
+	$(MAKE) $(AM_MAKEFLAGS) stage2scan.c; \
+	echo Comparing stage1scan.c and stage2scan.c; \
+	cmp stage1scan.c stage2scan.c || { \
+	  s=$$?; \
+	  echo "Bootstrap comparison failure!"; \
+	  exit $$s; \
+	}; \
+	echo Comparison successful.; \
+	echo success >$@
 
 dist-hook: scan.l flex$(EXEEXT)
 	chmod u+w $(distdir) && \
